var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/(home)/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__005k~i~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0lbmw.j.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rbjgwf._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bd0tfh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__079b.t1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_0kf0f6u._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(home)_page_actions_0vqllp-.js")
R.m(692218)
module.exports=R.m(692218).exports
